name: Member Onboarding

on:
  repository_dispatch:
    types: [member_added]

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create Welcome Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          username="${{ github.event.client_payload.username }}"
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d "{\"title\": \"Welcome $username!\", \"body\": \"Hi @$username,\n\nWelcome to Samarth's organization!\"}"
