name: Env workflow

on: workflow_dispatch

jobs: 
    dev-job:
        environment: DEV
        runs-on: ubuntu-latest
        steps:
            - name: Repo checkout
              uses: actions/checkout@v4

            - name: List the files in this repo
              run: ls -lrta

            - name: Run a simple script
              run: echo "Job is running in dev env"

            - name: Print Var,Sec in DEV env
              run: |
                echo "Varibale is ${{ vars.DEV_VAR1 }}"
                echo "Secret is ${{ secrets.DEV_SEC1 }}"


    test-job:
        environment: TEST
        needs: dev-job
        runs-on: ubuntu-latest
        steps: 
            - name: Repo checkout 
              uses: actions/checkout@v4

            - name: Simple script to confirm
              run: echo "Job is running in test env"

    prod-job:
        environment: PROD
        needs: test-job
        runs-on: demo-vm
        steps: 
            - name: Repo checkout
              uses: actions/checkout@v4
            
            - name: Print msg to confirm
              run: echo "Job is running in prod env"