name: Testing the reusable wf

on: workflow_dispatch

jobs:
    job-1:
        uses: ./.github/workflows/reusable-wf2.yml
        secrets:
            secret1: ${{ secrets.DOCKER_PASSWORD }}
        with:
            input-1: ${{ vars.DOCKER_USERNAME }}
            