name: My first workflow

on: workflow_dispatch
#schedule:
#- cron: "*/1 * * * *"
#push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
            - name: Chekout repo 
              uses: actions/checkout@v4
              
            - name: Welcome Message
              run: |
                   echo "My first gh actions job"
                   ls -lrta
                   cat README.md
             
            - name: Calling comp action to test cowsay prog
              uses: ./.github/custom-actions/hello-world
              
            
            # - name: List the files in this repo
            #   run: ls -lrt
            
            # - name: Read file
            #   run: cat README.md
