name: workflow for i/p in comp action

on: workflow_dispatch

jobs:
    greet-user:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: call to comp action
              uses: ./.github/custom-actions/comp-act-2
              with: 
                owner-name: ${{ github.repository_owner }}