name: My first workflow

on:
  workflow_dispatch: 
  push: 
    branches: testing-1

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Call reusable workflow
        uses: ./.SamarthMohanKumar/repo-1/.github/workflows/reusable-workflow.yml@testing-1
