name: My first workflow

on: workflow_dispatch
#schedule:
#- cron: "*/1 * * * *"
    push:
      testing-1

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
            - name: Call reusable workflow
              uses: ./.github/workflows/reusable-workflow.yml
              
            # - name: Welcome Message
            #   run: |
            #        echo "My first gh actions job"
            #        ls -lrta
            #        cat README.md

            # - name: Generate ASCII Art
            #   run: cowsay -f dragon "Run for life, I am a dragon.....:@" >> dragon.txt
              
            
            # - name: List the files in this repo
            #   run: ls -lrt
            
            # - name: Read file
            #   run: cat README.md
