name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
            - name: Welcome Message
              run: echo "My first gh actions job"
            
            - name: List the files in this repo
              run: ls -lrt
            
            - name: Read file
              run: cat README.md
