name: My first workflow

on: workflow_dispatch

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
            - name: Chekout repo 
              uses: actions/checkout@v4
              
            - name: Welcome Message
              run: |
                   echo "My first gh actions job"
                   ls -lrta
                   cat README.md
            
            - name: Installing cowsay files
              run: sudo apt get update && suso apt-get install -y cowsay

            - name: Generate tux Art
              run: cowsay -f tux "Run for your life, I am a penguin" >> penguin.txt
              
            
            # - name: List the files in this repo
            #   run: ls -lrt
            
            # - name: Read file
            #   run: cat README.md
