name: Generate artwork

on: workflow_dispatch

jobs: 
    ascii-artwork-job:
        runs-on: ubuntu-latest
        steps:
            - name: Repo checkout 
              uses: actions/checkout@v4
            
            - name: Install Cowsay program
              run: sudo apt-get install cowsay -y

            - name: Executeing a cowsay command
              run: cowsay -f elephant "Run for life, I am elephant...:@" >> elephant.txt

            - name: Test if dragon file exists or not
              run: grep -i "elephant" elephant.txt

            - name: Read file
              run: cat elephant.txt

            - name: Checkout files
              run: ls -lrta

              