name: Generate ASCII artwork

on: workflow_dispatch

jobs:
  build-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y 

      - name: Execute cowsay Command
        run: cowsay -f elephant "Run for your life, I am an Elephant...:@" >> elephant.txt

      - name: Upload elephant.txt artifact
        uses: actions/upload-artifact@v4
        with:
          name: elephant-file
          path:  elephant.txt


  test-job2:
    needs: build-job1
    runs-on: ubuntu-latest
    steps:
      - name: Download elephant file
        uses: actions/download-artifact@v4
        with:
          name: elephant-file

      - name: Test file exists
        run: grep -i "elephant" elephant.txt

  
  deploy-job3:
    runs-on: ubuntu-latest
    needs: test-job2
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: elephant-file
          
      - name: Read the elephant file
        run: cat elephant.txt

      - name: Deploy 
        run: echo "Deploying ..."