name: Generate ASCII artwork

on: push

jobs:
  build-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y 

      - name: Execute cowsay Command
        run: cowsay -f elephant "Run for your life, I am an Elephant...:@" >> elephant.txt

      - name: Sleep for 30 sec
        run: sleep 30

  test-job2:
    runs-on: ubuntu-latest
    steps:
      - name: sleep for 10 sec
        run: sleep 10

      - name: Test file exists
        run: grep -i "elephant" elephant.txt

  
  deploy-job3:
    runs-on: ubuntu-latest
    steps:
      - name: Read the elephant file
        run: cat elephant.txt

      - name: Deploy 
        run: echo "Deploying ..."