name: GitHub Scripts

on: 
    workflow_dispatch: 
    # push:
    #     branches: 
    #         - main

jobs:
    job-1:  
        runs-on: ubuntu-latest
        steps: 
            - name: View context attributes
              uses: actions/github-script@v7
              with:
                script: |
                        console.log(`The repository owner and repository name is  ${context.repo.owner}`);
                        console.log(`The repository you are working on is: ${context.repo.repo}`);
                        console.log(context);
