name: Sync GitHub Issue to JIRA (Real API Call)

on:
  issues:
    types: [opened]

jobs:
  sync-to-jira:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        env:
          JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
        with:
          script: |
            const title = context.payload.issue.title;
            const body = context.payload.issue.body || "";
            const issueUrl = context.payload.issue.html_url;

            const jiraDomain = process.env.JIRA_DOMAIN;
            const jiraEmail = process.env.JIRA_EMAIL;
            const jiraApiToken = process.env.JIRA_API_TOKEN;
            const jiraProjectKey = process.env.JIRA_PROJECT_KEY;

            const auth = Buffer.from(`${jiraEmail}:${jiraApiToken}`).toString('base64');

            const payload = {
              fields: {
                project: { key: jiraProjectKey },
                summary: title,
                description: `${body}\n\nGitHub Issue: ${issueUrl}`,
                issuetype: { name: "Task" }
              }
            };

            const res = await fetch(`https://${jiraDomain}/rest/api/2/issue`, {
              method: 'POST',
              headers: {
                'Authorization': `Basic ${auth}`,
                'Content-Type': 'application/json'
              },
              body: JSON.stringify(payload)
            });

            if (res.ok) {
              const data = await res.json();
              console.log(`JIRA Ticket created`);
            } else {
              console.error(`Failed to create JIRA ticket`);
              throw new Error("JIRA ticket creation failed");
            }
