name: Matrix workflow

on: workflow_dispatch

jobs:
    deploy:
        strategy:
            matrix:
                os: [ windows-latest, ubuntu-latest, ubuntu-20.04 ]
                images: [hello-world, alpine]
        runs-on: ${{ matrix.os }}
        steps:
            - name: echo docker info
              run: docker info

            - name: Run img on ${{ matrix.os }}
              run: docker run ${{ matrix.images }}

