name: Matrix workflow

on: workflow_dispatch

jobs:
    deploy:
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                os: [ windows-latest, ubuntu-latest, ubuntu-20.04 ]
                images: [hello-world, alpine]
                exclude:
                  - images: alpine
                    os: windows-latest
                include:
                  - images: amd64/alpine
                    os: ubuntu-20.04
        runs-on: ${{ matrix.os }}
        steps:
            - name: echo docker info
              run: docker info

            - name: Run img on ${{ matrix.os }}
              run: docker run ${{ matrix.images }}

