name: Get PR Title on Creation to main

on:
  workflow_dispatch: 
  # pull_request:
  #   types: [opened]

jobs:
  print-pr-title:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            console.log("PR Title: " + context.payload.pull_request.title);

