name: Reusable workflow

on: 
    workflow_call:
        inputs:
            input-1:
                required: true
                type: string
        secrets:
            secret1:
                required: true

jobs: 
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Get the docker password
              run: echo ${{ secrets.secret1 }}

            - name: Get the environemt variable 
              run: echo "Docker username is ${{ inputs.input-1 }}"