name: Reusable workflow

on: 
    workflow_call: 

jobs:
    Test-job1:
        name: test job1
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: |
                   echo "My first gh actions job"
                   ls -lrta
                   cat README.md

            - name: Generate ASCII Art
              run: cowsay -f dragon "Run for life, I am a dragon.....:@" >> dragon.txt
              
            - name: List the files in this repo
              run: ls -lrt
            
            - name: Read file
              run: cat README.md